<?php
include 'dbh.php';

function display_privacy_policy() {
    echo '<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Privacy Policy - Hernia Hub</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                line-height: 1.6;
                margin: 0;
                padding: 0;
                background-color: #f4f4f4;
            }
            .container {
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #fff;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            h1, h2, h3 {
                color: #333;
            }
            p {
                color: #555;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Privacy Policy</h1>
            <p>Welcome to Hernia Hub, an application focused on providing users with personalized health tools, including appointment booking, health records management, and profile customization. This Privacy Policy explains how we collect, use, and protect your personal information when you use our services.</p>

            <h2>Interpretation and Definitions</h2>
            <h3>Definitions</h3>
            <ul>
                <li><strong>Account:</strong> A unique account created for you to access our Service.</li>
                <li><strong>Application:</strong> Refers to Hernia Hub, the health management software provided by our company.</li>
                <li><strong>Company:</strong> Refers to the operators of Hernia Hub.</li>
                <li><strong>Country:</strong> Refers to the region of operation.</li>
                <li><strong>Device:</strong> Any device that can access the Service, such as a smartphone, computer, or tablet.</li>
                <li><strong>Personal Data:</strong> Information that relates to an identifiable person.</li>
                <li><strong>Service:</strong> Refers to Hernia Hub and its functionalities.</li>
                <li><strong>Service Provider:</strong> Any individual or company processing data on behalf of Hernia Hub.</li>
                <li><strong>Usage Data:</strong> Automatically collected data generated by the use of the Service.</li>
                <li><strong>You:</strong> Refers to the individual or entity using the Service.</li>
            </ul>

            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>

            <h4>Personal Data</h4>
            <p>While using our Service, we may ask you to provide certain personal information, including but not limited to:</p>
            <ul>
                <li>Name</li>
                <li>Age</li>
                <li>Email address</li>
                <li>Phone number</li>
                <li>Profile and other images</li>
            </ul>

            <h4>Appointment and Communication Data</h4>
            <p>To facilitate our services, we may collect data associated with your appointments, as well as messages exchanged through integrated chat tools like WhatsApp.</p>

            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service, including information such as IP address, browser type, the pages visited, and diagnostic data related to the app performance.</p>

            <h2>Using and Sharing Your Personal Data</h2>
            <p>Hernia Hub uses your data to provide and improve its services, including appointment scheduling, profile management, and health recommendations. We may share your data with Service Providers who assist us in maintaining the Service.</p>

            <h2>Retention of Your Personal Data</h2>
            <p>We retain your data only as long as necessary for the purposes specified in this policy and to comply with legal obligations.</p>

            <h2>Transfer of Your Personal Data</h2>
            <p>Your data may be transferred and stored outside of your country. By using Hernia Hub, you consent to such data transfers under secure conditions.</p>

            <h2>Disclosure of Your Personal Data</h2>
            <h3>Business Transactions</h3>
            <p>Your data may be transferred as part of business transactions like mergers or acquisitions. We will notify you before your data is transferred.</p>

            <h3>Legal Requirements</h3>
            <p>We may disclose your data if required by law or in response to valid requests by public authorities.</p>

            <h2>Security of Your Personal Data</h2>
            <p>We implement security measures to protect your data but cannot guarantee absolute security due to potential vulnerabilities.</p>

            <h2>Children\'s Privacy</h2>
            <p>Our Service does not target individuals under 13, and we do not knowingly collect data from children under this age. If you are a guardian and are aware of such data, please contact us to delete it.</p>

            <h2>Changes to this Privacy Policy</h2>
            <p>We may update this Privacy Policy, and any changes will be posted on this page. Please review it periodically for updates.</p>

            <h2>Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, you can contact us at <a href="mailto:praneethk480@gmail.com">praneethk480@gmail.com</a>.</p>

            <p>© 2024 Hernia Hub. All rights reserved.</p>
        </div>
    </body>
    </html>';
}

// Call the function to display the privacy policy
display_privacy_policy();
?>
